//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUnicam.Risorse {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dizionario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dizionario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyUnicam.Risorse.Dizionario", typeof(Dizionario).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aule.
        /// </summary>
        public static string Aule {
            get {
                return ResourceManager.GetString("Aule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studenti.
        /// </summary>
        public static string BannerStudenti {
            get {
                return ResourceManager.GetString("BannerStudenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Università.
        /// </summary>
        public static string BannerUniversita {
            get {
                return ResourceManager.GetString("BannerUniversita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai al canale YouTube.
        /// </summary>
        public static string CanaleYT {
            get {
                return ResourceManager.GetString("CanaleYT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicati Stampa.
        /// </summary>
        public static string ComunicatiStampa {
            get {
                return ResourceManager.GetString("ComunicatiStampa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leggi articolo.
        /// </summary>
        public static string ComunicatiStampaLeggi {
            get {
                return ResourceManager.GetString("ComunicatiStampaLeggi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsi di Laurea.
        /// </summary>
        public static string CorsiLaurea {
            get {
                return ResourceManager.GetString("CorsiLaurea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dettagli del corso.
        /// </summary>
        public static string DettaglioCorso {
            get {
                return ResourceManager.GetString("DettaglioCorso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai al sito della carriera.
        /// </summary>
        public static string DidatticaLink {
            get {
                return ResourceManager.GetString("DidatticaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhD Courses.
        /// </summary>
        public static string dottorato {
            get {
                return ResourceManager.GetString("dottorato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Utente o Password errati.
        /// </summary>
        public static string ErroreDiLogin {
            get {
                return ResourceManager.GetString("ErroreDiLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventi.
        /// </summary>
        public static string Eventi {
            get {
                return ResourceManager.GetString("Eventi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingue.
        /// </summary>
        public static string Lingue {
            get {
                return ResourceManager.GetString("Lingue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Carriera.
        /// </summary>
        public static string LoginCarriera {
            get {
                return ResourceManager.GetString("LoginCarriera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsi di Laurea Magistrale.
        /// </summary>
        public static string magistrale {
            get {
                return ResourceManager.GetString("magistrale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsi di Laurea Magistrale a ciclo unico.
        /// </summary>
        public static string magunico {
            get {
                return ResourceManager.GetString("magunico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappa.
        /// </summary>
        public static string Mappa {
            get {
                return ResourceManager.GetString("Mappa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappa Sedi.
        /// </summary>
        public static string MappaSedi {
            get {
                return ResourceManager.GetString("MappaSedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offerta Formativa.
        /// </summary>
        public static string OffertaFormativa {
            get {
                return ResourceManager.GetString("OffertaFormativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orario Lezioni.
        /// </summary>
        public static string OrarioLezioni {
            get {
                return ResourceManager.GetString("OrarioLezioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEZIONI PREFERITE.
        /// </summary>
        public static string PagineVisitate {
            get {
                return ResourceManager.GetString("PagineVisitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master di primo livello.
        /// </summary>
        public static string primomaster {
            get {
                return ResourceManager.GetString("primomaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubrica.
        /// </summary>
        public static string Rubrica {
            get {
                return ResourceManager.GetString("Rubrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string RubricaCancel {
            get {
                return ResourceManager.GetString("RubricaCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RubricaEmail {
            get {
                return ResourceManager.GetString("RubricaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiamata.
        /// </summary>
        public static string RubricaTelefono {
            get {
                return ResourceManager.GetString("RubricaTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatta via:.
        /// </summary>
        public static string RubricaTitoloPopUp {
            get {
                return ResourceManager.GetString("RubricaTitoloPopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master di secondo livello.
        /// </summary>
        public static string secondomaster {
            get {
                return ResourceManager.GetString("secondomaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedi.
        /// </summary>
        public static string Sedi {
            get {
                return ResourceManager.GetString("Sedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scuole di Specializzazione.
        /// </summary>
        public static string specialistica {
            get {
                return ResourceManager.GetString("specialistica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFA - Tirocini Formativi Attivi.
        /// </summary>
        public static string tfa {
            get {
                return ResourceManager.GetString("tfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsi di Laurea.
        /// </summary>
        public static string triennale {
            get {
                return ResourceManager.GetString("triennale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
