//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUnicam.Esse3Carriera {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Studente", Namespace="http://utils.soapesse3.unicam.it")]
    public partial class Studente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codFisField;
        
        private string nomeField;
        
        private string cognomeField;
        
        private string sessoField;
        
        private string dataELuogoNascitaField;
        
        private string usernameField;
        
        private string emailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codFis {
            get {
                return this.codFisField;
            }
            set {
                if ((object.ReferenceEquals(this.codFisField, value) != true)) {
                    this.codFisField = value;
                    this.RaisePropertyChanged("codFis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string cognome {
            get {
                return this.cognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.cognomeField, value) != true)) {
                    this.cognomeField = value;
                    this.RaisePropertyChanged("cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string sesso {
            get {
                return this.sessoField;
            }
            set {
                if ((object.ReferenceEquals(this.sessoField, value) != true)) {
                    this.sessoField = value;
                    this.RaisePropertyChanged("sesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string dataELuogoNascita {
            get {
                return this.dataELuogoNascitaField;
            }
            set {
                if ((object.ReferenceEquals(this.dataELuogoNascitaField, value) != true)) {
                    this.dataELuogoNascitaField = value;
                    this.RaisePropertyChanged("dataELuogoNascita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Esame", Namespace="http://utils.soapesse3.unicam.it")]
    public partial class Esame : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int annoDiCorsoField;
        
        private string codiceField;
        
        private string nomeField;
        
        private string statoField;
        
        private int aaFreqField;
        
        private float cfuField;
        
        private System.Nullable<System.DateTime> dataEsameField;
        
        private float votoField;
        
        private bool lodeField;
        
        private bool noMediaField;
        
        private string giudizioAltField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int annoDiCorso {
            get {
                return this.annoDiCorsoField;
            }
            set {
                if ((this.annoDiCorsoField.Equals(value) != true)) {
                    this.annoDiCorsoField = value;
                    this.RaisePropertyChanged("annoDiCorso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codice {
            get {
                return this.codiceField;
            }
            set {
                if ((object.ReferenceEquals(this.codiceField, value) != true)) {
                    this.codiceField = value;
                    this.RaisePropertyChanged("codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int aaFreq {
            get {
                return this.aaFreqField;
            }
            set {
                if ((this.aaFreqField.Equals(value) != true)) {
                    this.aaFreqField = value;
                    this.RaisePropertyChanged("aaFreq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public float cfu {
            get {
                return this.cfuField;
            }
            set {
                if ((this.cfuField.Equals(value) != true)) {
                    this.cfuField = value;
                    this.RaisePropertyChanged("cfu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> dataEsame {
            get {
                return this.dataEsameField;
            }
            set {
                if ((this.dataEsameField.Equals(value) != true)) {
                    this.dataEsameField = value;
                    this.RaisePropertyChanged("dataEsame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public float voto {
            get {
                return this.votoField;
            }
            set {
                if ((this.votoField.Equals(value) != true)) {
                    this.votoField = value;
                    this.RaisePropertyChanged("voto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool lode {
            get {
                return this.lodeField;
            }
            set {
                if ((this.lodeField.Equals(value) != true)) {
                    this.lodeField = value;
                    this.RaisePropertyChanged("lode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool noMedia {
            get {
                return this.noMediaField;
            }
            set {
                if ((this.noMediaField.Equals(value) != true)) {
                    this.noMediaField = value;
                    this.RaisePropertyChanged("noMedia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public string giudizioAlt {
            get {
                return this.giudizioAltField;
            }
            set {
                if ((object.ReferenceEquals(this.giudizioAltField, value) != true)) {
                    this.giudizioAltField = value;
                    this.RaisePropertyChanged("giudizioAlt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorsoDiStudio", Namespace="http://utils.soapesse3.unicam.it")]
    public partial class CorsoDiStudio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int stuIdField;
        
        private string matricolaField;
        
        private string corsoDiStudioField;
        
        private string percorsoDiStudioField;
        
        private string statoField;
        
        private float maxPuntiField;
        
        private float cfuField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int stuId {
            get {
                return this.stuIdField;
            }
            set {
                if ((this.stuIdField.Equals(value) != true)) {
                    this.stuIdField = value;
                    this.RaisePropertyChanged("stuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string matricola {
            get {
                return this.matricolaField;
            }
            set {
                if ((object.ReferenceEquals(this.matricolaField, value) != true)) {
                    this.matricolaField = value;
                    this.RaisePropertyChanged("matricola");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string corsoDiStudio {
            get {
                return this.corsoDiStudioField;
            }
            set {
                if ((object.ReferenceEquals(this.corsoDiStudioField, value) != true)) {
                    this.corsoDiStudioField = value;
                    this.RaisePropertyChanged("corsoDiStudio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string percorsoDiStudio {
            get {
                return this.percorsoDiStudioField;
            }
            set {
                if ((object.ReferenceEquals(this.percorsoDiStudioField, value) != true)) {
                    this.percorsoDiStudioField = value;
                    this.RaisePropertyChanged("percorsoDiStudio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string stato {
            get {
                return this.statoField;
            }
            set {
                if ((object.ReferenceEquals(this.statoField, value) != true)) {
                    this.statoField = value;
                    this.RaisePropertyChanged("stato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public float maxPunti {
            get {
                return this.maxPuntiField;
            }
            set {
                if ((this.maxPuntiField.Equals(value) != true)) {
                    this.maxPuntiField = value;
                    this.RaisePropertyChanged("maxPunti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public float cfu {
            get {
                return this.cfuField;
            }
            set {
                if ((this.cfuField.Equals(value) != true)) {
                    this.cfuField = value;
                    this.RaisePropertyChanged("cfu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soapesse3.unicam.it", ConfigurationName="Esse3Carriera.Esse3StudentWS")]
    public interface Esse3StudentWS {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetAnagrafe(MyUnicam.Esse3Carriera.getAnagrafeRequest request, System.AsyncCallback callback, object asyncState);
        
        MyUnicam.Esse3Carriera.getAnagrafeResponse EndgetAnagrafe(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetCarriera(MyUnicam.Esse3Carriera.getCarrieraRequest request, System.AsyncCallback callback, object asyncState);
        
        MyUnicam.Esse3Carriera.getCarrieraResponse EndgetCarriera(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetCorsi(MyUnicam.Esse3Carriera.getCorsiRequest request, System.AsyncCallback callback, object asyncState);
        
        MyUnicam.Esse3Carriera.getCorsiResponse EndgetCorsi(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginlogout(MyUnicam.Esse3Carriera.logoutRequest request, System.AsyncCallback callback, object asyncState);
        
        MyUnicam.Esse3Carriera.logoutResponse Endlogout(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginlogin(MyUnicam.Esse3Carriera.loginRequest request, System.AsyncCallback callback, object asyncState);
        
        MyUnicam.Esse3Carriera.loginResponse Endlogin(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getAnagrafeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAnagrafe", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.getAnagrafeRequestBody Body;
        
        public getAnagrafeRequest() {
        }
        
        public getAnagrafeRequest(MyUnicam.Esse3Carriera.getAnagrafeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class getAnagrafeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public getAnagrafeRequestBody() {
        }
        
        public getAnagrafeRequestBody(string username, string token) {
            this.username = username;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getAnagrafeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAnagrafeResponse", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.getAnagrafeResponseBody Body;
        
        public getAnagrafeResponse() {
        }
        
        public getAnagrafeResponse(MyUnicam.Esse3Carriera.getAnagrafeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class getAnagrafeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyUnicam.Esse3Carriera.Studente getAnagrafeReturn;
        
        public getAnagrafeResponseBody() {
        }
        
        public getAnagrafeResponseBody(MyUnicam.Esse3Carriera.Studente getAnagrafeReturn) {
            this.getAnagrafeReturn = getAnagrafeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getCarrieraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCarriera", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.getCarrieraRequestBody Body;
        
        public getCarrieraRequest() {
        }
        
        public getCarrieraRequest(MyUnicam.Esse3Carriera.getCarrieraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class getCarrieraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string matricola;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public getCarrieraRequestBody() {
        }
        
        public getCarrieraRequestBody(string username, string matricola, string token) {
            this.username = username;
            this.matricola = matricola;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getCarrieraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCarrieraResponse", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.getCarrieraResponseBody Body;
        
        public getCarrieraResponse() {
        }
        
        public getCarrieraResponse(MyUnicam.Esse3Carriera.getCarrieraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class getCarrieraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyUnicam.Esse3Carriera.Esame getCarrieraReturn;
        
        public getCarrieraResponseBody() {
        }
        
        public getCarrieraResponseBody(MyUnicam.Esse3Carriera.Esame getCarrieraReturn) {
            this.getCarrieraReturn = getCarrieraReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getCorsiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCorsi", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.getCorsiRequestBody Body;
        
        public getCorsiRequest() {
        }
        
        public getCorsiRequest(MyUnicam.Esse3Carriera.getCorsiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class getCorsiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public getCorsiRequestBody() {
        }
        
        public getCorsiRequestBody(string username, string token) {
            this.username = username;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class getCorsiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCorsiResponse", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.getCorsiResponseBody Body;
        
        public getCorsiResponse() {
        }
        
        public getCorsiResponse(MyUnicam.Esse3Carriera.getCorsiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class getCorsiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyUnicam.Esse3Carriera.CorsoDiStudio getCorsiReturn;
        
        public getCorsiResponseBody() {
        }
        
        public getCorsiResponseBody(MyUnicam.Esse3Carriera.CorsoDiStudio getCorsiReturn) {
            this.getCorsiReturn = getCorsiReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logout", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.logoutRequestBody Body;
        
        public logoutRequest() {
        }
        
        public logoutRequest(MyUnicam.Esse3Carriera.logoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class logoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public logoutRequestBody() {
        }
        
        public logoutRequestBody(string username, string token) {
            this.username = username;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.logoutResponseBody Body;
        
        public logoutResponse() {
        }
        
        public logoutResponse(MyUnicam.Esse3Carriera.logoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class logoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logoutReturn;
        
        public logoutResponseBody() {
        }
        
        public logoutResponseBody(bool logoutReturn) {
            this.logoutReturn = logoutReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(MyUnicam.Esse3Carriera.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://soapesse3.unicam.it", Order=0)]
        public MyUnicam.Esse3Carriera.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(MyUnicam.Esse3Carriera.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://soapesse3.unicam.it")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginReturn;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginReturn) {
            this.loginReturn = loginReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Esse3StudentWSChannel : MyUnicam.Esse3Carriera.Esse3StudentWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAnagrafeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAnagrafeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MyUnicam.Esse3Carriera.Studente Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MyUnicam.Esse3Carriera.Studente)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getCarrieraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getCarrieraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MyUnicam.Esse3Carriera.Esame Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MyUnicam.Esse3Carriera.Esame)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getCorsiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getCorsiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MyUnicam.Esse3Carriera.CorsoDiStudio Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MyUnicam.Esse3Carriera.CorsoDiStudio)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class logoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public logoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Esse3StudentWSClient : System.ServiceModel.ClientBase<MyUnicam.Esse3Carriera.Esse3StudentWS>, MyUnicam.Esse3Carriera.Esse3StudentWS {
        
        private BeginOperationDelegate onBegingetAnagrafeDelegate;
        
        private EndOperationDelegate onEndgetAnagrafeDelegate;
        
        private System.Threading.SendOrPostCallback ongetAnagrafeCompletedDelegate;
        
        private BeginOperationDelegate onBegingetCarrieraDelegate;
        
        private EndOperationDelegate onEndgetCarrieraDelegate;
        
        private System.Threading.SendOrPostCallback ongetCarrieraCompletedDelegate;
        
        private BeginOperationDelegate onBegingetCorsiDelegate;
        
        private EndOperationDelegate onEndgetCorsiDelegate;
        
        private System.Threading.SendOrPostCallback ongetCorsiCompletedDelegate;
        
        private BeginOperationDelegate onBeginlogoutDelegate;
        
        private EndOperationDelegate onEndlogoutDelegate;
        
        private System.Threading.SendOrPostCallback onlogoutCompletedDelegate;
        
        private BeginOperationDelegate onBeginloginDelegate;
        
        private EndOperationDelegate onEndloginDelegate;
        
        private System.Threading.SendOrPostCallback onloginCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Esse3StudentWSClient() : 
                base(Esse3StudentWSClient.GetDefaultBinding(), Esse3StudentWSClient.GetDefaultEndpointAddress()) {
        }
        
        public Esse3StudentWSClient(EndpointConfiguration endpointConfiguration) : 
                base(Esse3StudentWSClient.GetBindingForEndpoint(endpointConfiguration), Esse3StudentWSClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public Esse3StudentWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Esse3StudentWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public Esse3StudentWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Esse3StudentWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public Esse3StudentWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getAnagrafeCompletedEventArgs> getAnagrafeCompleted;
        
        public event System.EventHandler<getCarrieraCompletedEventArgs> getCarrieraCompleted;
        
        public event System.EventHandler<getCorsiCompletedEventArgs> getCorsiCompleted;
        
        public event System.EventHandler<logoutCompletedEventArgs> logoutCompleted;
        
        public event System.EventHandler<loginCompletedEventArgs> loginCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyUnicam.Esse3Carriera.Esse3StudentWS.BegingetAnagrafe(MyUnicam.Esse3Carriera.getAnagrafeRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAnagrafe(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetAnagrafe(string username, string token, System.AsyncCallback callback, object asyncState) {
            MyUnicam.Esse3Carriera.getAnagrafeRequest inValue = new MyUnicam.Esse3Carriera.getAnagrafeRequest();
            inValue.Body = new MyUnicam.Esse3Carriera.getAnagrafeRequestBody();
            inValue.Body.username = username;
            inValue.Body.token = token;
            return ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).BegingetAnagrafe(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyUnicam.Esse3Carriera.getAnagrafeResponse MyUnicam.Esse3Carriera.Esse3StudentWS.EndgetAnagrafe(System.IAsyncResult result) {
            return base.Channel.EndgetAnagrafe(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private MyUnicam.Esse3Carriera.Studente EndgetAnagrafe(System.IAsyncResult result) {
            MyUnicam.Esse3Carriera.getAnagrafeResponse retVal = ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).EndgetAnagrafe(result);
            return retVal.Body.getAnagrafeReturn;
        }
        
        private System.IAsyncResult OnBegingetAnagrafe(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string token = ((string)(inValues[1]));
            return this.BegingetAnagrafe(username, token, callback, asyncState);
        }
        
        private object[] OnEndgetAnagrafe(System.IAsyncResult result) {
            MyUnicam.Esse3Carriera.Studente retVal = this.EndgetAnagrafe(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAnagrafeCompleted(object state) {
            if ((this.getAnagrafeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAnagrafeCompleted(this, new getAnagrafeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAnagrafeAsync(string username, string token) {
            this.getAnagrafeAsync(username, token, null);
        }
        
        public void getAnagrafeAsync(string username, string token, object userState) {
            if ((this.onBegingetAnagrafeDelegate == null)) {
                this.onBegingetAnagrafeDelegate = new BeginOperationDelegate(this.OnBegingetAnagrafe);
            }
            if ((this.onEndgetAnagrafeDelegate == null)) {
                this.onEndgetAnagrafeDelegate = new EndOperationDelegate(this.OnEndgetAnagrafe);
            }
            if ((this.ongetAnagrafeCompletedDelegate == null)) {
                this.ongetAnagrafeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAnagrafeCompleted);
            }
            base.InvokeAsync(this.onBegingetAnagrafeDelegate, new object[] {
                        username,
                        token}, this.onEndgetAnagrafeDelegate, this.ongetAnagrafeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyUnicam.Esse3Carriera.Esse3StudentWS.BegingetCarriera(MyUnicam.Esse3Carriera.getCarrieraRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetCarriera(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetCarriera(string username, string matricola, string token, System.AsyncCallback callback, object asyncState) {
            MyUnicam.Esse3Carriera.getCarrieraRequest inValue = new MyUnicam.Esse3Carriera.getCarrieraRequest();
            inValue.Body = new MyUnicam.Esse3Carriera.getCarrieraRequestBody();
            inValue.Body.username = username;
            inValue.Body.matricola = matricola;
            inValue.Body.token = token;
            return ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).BegingetCarriera(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyUnicam.Esse3Carriera.getCarrieraResponse MyUnicam.Esse3Carriera.Esse3StudentWS.EndgetCarriera(System.IAsyncResult result) {
            return base.Channel.EndgetCarriera(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private MyUnicam.Esse3Carriera.Esame EndgetCarriera(System.IAsyncResult result) {
            MyUnicam.Esse3Carriera.getCarrieraResponse retVal = ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).EndgetCarriera(result);
            return retVal.Body.getCarrieraReturn;
        }
        
        private System.IAsyncResult OnBegingetCarriera(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string matricola = ((string)(inValues[1]));
            string token = ((string)(inValues[2]));
            return this.BegingetCarriera(username, matricola, token, callback, asyncState);
        }
        
        private object[] OnEndgetCarriera(System.IAsyncResult result) {
            MyUnicam.Esse3Carriera.Esame retVal = this.EndgetCarriera(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetCarrieraCompleted(object state) {
            if ((this.getCarrieraCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getCarrieraCompleted(this, new getCarrieraCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getCarrieraAsync(string username, string matricola, string token) {
            this.getCarrieraAsync(username, matricola, token, null);
        }
        
        public void getCarrieraAsync(string username, string matricola, string token, object userState) {
            if ((this.onBegingetCarrieraDelegate == null)) {
                this.onBegingetCarrieraDelegate = new BeginOperationDelegate(this.OnBegingetCarriera);
            }
            if ((this.onEndgetCarrieraDelegate == null)) {
                this.onEndgetCarrieraDelegate = new EndOperationDelegate(this.OnEndgetCarriera);
            }
            if ((this.ongetCarrieraCompletedDelegate == null)) {
                this.ongetCarrieraCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetCarrieraCompleted);
            }
            base.InvokeAsync(this.onBegingetCarrieraDelegate, new object[] {
                        username,
                        matricola,
                        token}, this.onEndgetCarrieraDelegate, this.ongetCarrieraCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyUnicam.Esse3Carriera.Esse3StudentWS.BegingetCorsi(MyUnicam.Esse3Carriera.getCorsiRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetCorsi(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BegingetCorsi(string username, string token, System.AsyncCallback callback, object asyncState) {
            MyUnicam.Esse3Carriera.getCorsiRequest inValue = new MyUnicam.Esse3Carriera.getCorsiRequest();
            inValue.Body = new MyUnicam.Esse3Carriera.getCorsiRequestBody();
            inValue.Body.username = username;
            inValue.Body.token = token;
            return ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).BegingetCorsi(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyUnicam.Esse3Carriera.getCorsiResponse MyUnicam.Esse3Carriera.Esse3StudentWS.EndgetCorsi(System.IAsyncResult result) {
            return base.Channel.EndgetCorsi(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private MyUnicam.Esse3Carriera.CorsoDiStudio EndgetCorsi(System.IAsyncResult result) {
            MyUnicam.Esse3Carriera.getCorsiResponse retVal = ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).EndgetCorsi(result);
            return retVal.Body.getCorsiReturn;
        }
        
        private System.IAsyncResult OnBegingetCorsi(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string token = ((string)(inValues[1]));
            return this.BegingetCorsi(username, token, callback, asyncState);
        }
        
        private object[] OnEndgetCorsi(System.IAsyncResult result) {
            MyUnicam.Esse3Carriera.CorsoDiStudio retVal = this.EndgetCorsi(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetCorsiCompleted(object state) {
            if ((this.getCorsiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getCorsiCompleted(this, new getCorsiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getCorsiAsync(string username, string token) {
            this.getCorsiAsync(username, token, null);
        }
        
        public void getCorsiAsync(string username, string token, object userState) {
            if ((this.onBegingetCorsiDelegate == null)) {
                this.onBegingetCorsiDelegate = new BeginOperationDelegate(this.OnBegingetCorsi);
            }
            if ((this.onEndgetCorsiDelegate == null)) {
                this.onEndgetCorsiDelegate = new EndOperationDelegate(this.OnEndgetCorsi);
            }
            if ((this.ongetCorsiCompletedDelegate == null)) {
                this.ongetCorsiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetCorsiCompleted);
            }
            base.InvokeAsync(this.onBegingetCorsiDelegate, new object[] {
                        username,
                        token}, this.onEndgetCorsiDelegate, this.ongetCorsiCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyUnicam.Esse3Carriera.Esse3StudentWS.Beginlogout(MyUnicam.Esse3Carriera.logoutRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginlogout(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginlogout(string username, string token, System.AsyncCallback callback, object asyncState) {
            MyUnicam.Esse3Carriera.logoutRequest inValue = new MyUnicam.Esse3Carriera.logoutRequest();
            inValue.Body = new MyUnicam.Esse3Carriera.logoutRequestBody();
            inValue.Body.username = username;
            inValue.Body.token = token;
            return ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).Beginlogout(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyUnicam.Esse3Carriera.logoutResponse MyUnicam.Esse3Carriera.Esse3StudentWS.Endlogout(System.IAsyncResult result) {
            return base.Channel.Endlogout(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool Endlogout(System.IAsyncResult result) {
            MyUnicam.Esse3Carriera.logoutResponse retVal = ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).Endlogout(result);
            return retVal.Body.logoutReturn;
        }
        
        private System.IAsyncResult OnBeginlogout(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string token = ((string)(inValues[1]));
            return this.Beginlogout(username, token, callback, asyncState);
        }
        
        private object[] OnEndlogout(System.IAsyncResult result) {
            bool retVal = this.Endlogout(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlogoutCompleted(object state) {
            if ((this.logoutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.logoutCompleted(this, new logoutCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void logoutAsync(string username, string token) {
            this.logoutAsync(username, token, null);
        }
        
        public void logoutAsync(string username, string token, object userState) {
            if ((this.onBeginlogoutDelegate == null)) {
                this.onBeginlogoutDelegate = new BeginOperationDelegate(this.OnBeginlogout);
            }
            if ((this.onEndlogoutDelegate == null)) {
                this.onEndlogoutDelegate = new EndOperationDelegate(this.OnEndlogout);
            }
            if ((this.onlogoutCompletedDelegate == null)) {
                this.onlogoutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlogoutCompleted);
            }
            base.InvokeAsync(this.onBeginlogoutDelegate, new object[] {
                        username,
                        token}, this.onEndlogoutDelegate, this.onlogoutCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyUnicam.Esse3Carriera.Esse3StudentWS.Beginlogin(MyUnicam.Esse3Carriera.loginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginlogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult Beginlogin(string username, string password, System.AsyncCallback callback, object asyncState) {
            MyUnicam.Esse3Carriera.loginRequest inValue = new MyUnicam.Esse3Carriera.loginRequest();
            inValue.Body = new MyUnicam.Esse3Carriera.loginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).Beginlogin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyUnicam.Esse3Carriera.loginResponse MyUnicam.Esse3Carriera.Esse3StudentWS.Endlogin(System.IAsyncResult result) {
            return base.Channel.Endlogin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string Endlogin(System.IAsyncResult result) {
            MyUnicam.Esse3Carriera.loginResponse retVal = ((MyUnicam.Esse3Carriera.Esse3StudentWS)(this)).Endlogin(result);
            return retVal.Body.loginReturn;
        }
        
        private System.IAsyncResult OnBeginlogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.Beginlogin(username, password, callback, asyncState);
        }
        
        private object[] OnEndlogin(System.IAsyncResult result) {
            string retVal = this.Endlogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnloginCompleted(object state) {
            if ((this.loginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.loginCompleted(this, new loginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void loginAsync(string username, string password) {
            this.loginAsync(username, password, null);
        }
        
        public void loginAsync(string username, string password, object userState) {
            if ((this.onBeginloginDelegate == null)) {
                this.onBeginloginDelegate = new BeginOperationDelegate(this.OnBeginlogin);
            }
            if ((this.onEndloginDelegate == null)) {
                this.onEndloginDelegate = new EndOperationDelegate(this.OnEndlogin);
            }
            if ((this.onloginCompletedDelegate == null)) {
                this.onloginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnloginCompleted);
            }
            base.InvokeAsync(this.onBeginloginDelegate, new object[] {
                        username,
                        password}, this.onEndloginDelegate, this.onloginCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MyUnicam.Esse3Carriera.Esse3StudentWS CreateChannel() {
            return new Esse3StudentWSClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.Esse3StudentWS)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.Esse3StudentWS)) {
                return new System.ServiceModel.EndpointAddress("https://analyzer.cs.unicam.it:8443/LibrettoWS1.6/services/Esse3StudentWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return Esse3StudentWSClient.GetBindingForEndpoint(EndpointConfiguration.Esse3StudentWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return Esse3StudentWSClient.GetEndpointAddress(EndpointConfiguration.Esse3StudentWS);
        }
        
        private class Esse3StudentWSClientChannel : ChannelBase<MyUnicam.Esse3Carriera.Esse3StudentWS>, MyUnicam.Esse3Carriera.Esse3StudentWS {
            
            public Esse3StudentWSClientChannel(System.ServiceModel.ClientBase<MyUnicam.Esse3Carriera.Esse3StudentWS> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetAnagrafe(MyUnicam.Esse3Carriera.getAnagrafeRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getAnagrafe", _args, callback, asyncState);
                return _result;
            }
            
            public MyUnicam.Esse3Carriera.getAnagrafeResponse EndgetAnagrafe(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyUnicam.Esse3Carriera.getAnagrafeResponse _result = ((MyUnicam.Esse3Carriera.getAnagrafeResponse)(base.EndInvoke("getAnagrafe", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetCarriera(MyUnicam.Esse3Carriera.getCarrieraRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getCarriera", _args, callback, asyncState);
                return _result;
            }
            
            public MyUnicam.Esse3Carriera.getCarrieraResponse EndgetCarriera(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyUnicam.Esse3Carriera.getCarrieraResponse _result = ((MyUnicam.Esse3Carriera.getCarrieraResponse)(base.EndInvoke("getCarriera", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetCorsi(MyUnicam.Esse3Carriera.getCorsiRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("getCorsi", _args, callback, asyncState);
                return _result;
            }
            
            public MyUnicam.Esse3Carriera.getCorsiResponse EndgetCorsi(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyUnicam.Esse3Carriera.getCorsiResponse _result = ((MyUnicam.Esse3Carriera.getCorsiResponse)(base.EndInvoke("getCorsi", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginlogout(MyUnicam.Esse3Carriera.logoutRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("logout", _args, callback, asyncState);
                return _result;
            }
            
            public MyUnicam.Esse3Carriera.logoutResponse Endlogout(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyUnicam.Esse3Carriera.logoutResponse _result = ((MyUnicam.Esse3Carriera.logoutResponse)(base.EndInvoke("logout", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginlogin(MyUnicam.Esse3Carriera.loginRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("login", _args, callback, asyncState);
                return _result;
            }
            
            public MyUnicam.Esse3Carriera.loginResponse Endlogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyUnicam.Esse3Carriera.loginResponse _result = ((MyUnicam.Esse3Carriera.loginResponse)(base.EndInvoke("login", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            Esse3StudentWS,
        }
    }
}
